//----------------------------------------------------
//	DOMLoader.script.js : 0.1.2 : 2012/09/08 : http://mudcu.be
//	----------------------------------------------------
//	Copyright 2011-2012 Mudcube. All rights reserved.
//	----------------------------------------------------
if("undefined"===typeof DOMLoader)var DOMLoader={};
(function(){DOMLoader.script=function(){this.loaded={};this.loading={};return this};DOMLoader.script.prototype.add=function(a){var c=this;"string"===typeof a&&(a={src:a});var b=a.srcs;"undefined"===typeof b&&(b=[{src:a.src,verify:a.verify}]);var e=document.getElementsByTagName("head")[0],l=function(a,b){if(!(c.loaded[a.src]||b&&"undefined"===typeof window[b])){c.loaded[a.src]=!0;if(c.loading[a.src])c.loading[a.src]();delete c.loading[a.src];a.callback&&a.callback();"undefined"!==typeof k&&k()}},m=
[],f=function(b){"string"===typeof b&&(b={src:b,verify:a.verify});if(/([\w\d.])$/.test(b.verify))if(b.test=b.verify,"object"===typeof b.test)for(var d in b.test)m.push(b.test[d]);else m.push(b.test);c.loaded[b.src]||(d=document.createElement("script"),d.onreadystatechange=function(){"loaded"!==this.readyState&&"complete"!==this.readyState||l(b)},d.onload=function(){l(b)},d.onerror=function(){},d.setAttribute("type","text/javascript"),d.setAttribute("src",b.src),e.appendChild(d),c.loading[b.src]=function(){})},
n=function(c){if(c)l(c,c.test);else for(var d=0;d<b.length;d++)l(b[d],b[d].test);for(var e=!0,d=0;d<m.length;d++){var g=m[d];if(g&&-1!==g.indexOf(".")){var g=g.split("."),f=window[g[0]];"undefined"!==typeof f&&(2===g.length?"undefined"===typeof f[g[1]]&&(e=!1):3===g.length&&"undefined"===typeof f[g[1]][g[2]]&&(e=!1))}else"undefined"===typeof window[g]&&(e=!1)}!a.strictOrder&&e?a.callback&&a.callback():setTimeout(function(){n(c)},10)};if(a.strictOrder){var h=-1,k=function(){h++;if(b[h]){var e=b[h],
d=e.src;c.loading[d]?c.loading[d]=function(){e.callback&&e.callback();k()}:c.loaded[d]?k():(f(e),n(e))}else a.callback&&a.callback()};k()}else{for(h=0;h<b.length;h++)f(b[h]);n()}};DOMLoader.script=new DOMLoader.script})();"undefined"===typeof DOMLoader&&(DOMLoader={});
if("undefined"===typeof XMLHttpRequest){var XMLHttpRequest;(function(){for(var a=[function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}],c=0;c<a.length;c++){try{a[c]()}catch(b){continue}break}XMLHttpRequest=a[c]})()}
if("undefined"===typeof(new XMLHttpRequest).responseText){var IEBinaryToArray_ByteStr_Script="\x3c!-- IEBinaryToArray_ByteStr --\x3e\r\n<script type='text/vbscript'>\r\nFunction IEBinaryToArray_ByteStr(Binary)\r\n   IEBinaryToArray_ByteStr = CStr(Binary)\r\nEnd Function\r\nFunction IEBinaryToArray_ByteStr_Last(Binary)\r\n   Dim lastIndex\r\n   lastIndex = LenB(Binary)\r\n   if lastIndex mod 2 Then\r\n       IEBinaryToArray_ByteStr_Last = Chr( AscB( MidB( Binary, lastIndex, 1 ) ) )\r\n   Else\r\n       IEBinaryToArray_ByteStr_Last = \"\"\r\n   End If\r\nEnd Function\r\n\x3c/script>\r\n";document.write(IEBinaryToArray_ByteStr_Script);
DOMLoader.sendRequest=function(a){function c(a){for(var b={},c=0;256>c;c++)for(var f=0;256>f;f++)b[String.fromCharCode(c+256*f)]=String.fromCharCode(c)+String.fromCharCode(f);c=IEBinaryToArray_ByteStr(a);a=IEBinaryToArray_ByteStr_Last(a);return c.replace(/[\s\S]/g,function(a){return b[a]})+a}var b=XMLHttpRequest();b.open("GET",a.url,!0);a.responseType&&(b.responseType=a.responseType);a.onerror&&(b.onerror=a.onerror);a.onprogress&&(b.onprogress=a.onprogress);b.onreadystatechange=function(e){if(4===
b.readyState&&(200===b.status?b.responseText=c(b.responseBody):b=!1,a.onload))a.onload(b)};b.setRequestHeader("Accept-Charset","x-user-defined");b.send(null);return b}}else DOMLoader.sendRequest=function(a){var c=new XMLHttpRequest;c.open(a.data?"POST":"GET",a.url,!0);c.overrideMimeType&&c.overrideMimeType("text/plain; charset=x-user-defined");a.data&&c.setRequestHeader("Content-type","application/javascript");a.responseType&&(c.responseType=a.responseType);a.onerror&&(c.onerror=a.onerror);
a.onprogress&&(c.onprogress=a.onprogress);c.onreadystatechange=function(b){if(4===c.readyState)if(200!==c.status&&304!=c.status){if(a.onerror)a.onerror(b,!1)}else if(a.onload)a.onload(c)};c.send(a.data);return c};